#!/usr/local/bin/python -u

import sys,os,logging,re
sys.path.append("/xtra/www/webroot/nm/cgi-bin")
sys.path.append("/usr/local/bin")
from ticutil import EXENAME,EXEPATH,errorexit
import ticutil

import ticinfoblox

import datetime
import nmrest
import json

#------------------------------------------------------------------------------
# GLOBALS
#------------------------------------------------------------------------------

logger=logging.getLogger(__name__)
G_queryDate = datetime.datetime.today().strftime("%A, %B %d, %Y at %I:%M%p")
G_IPADDRESS_PATTERN = re.compile(r"^(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)$")
